# Generated by Django 3.2 on 2021-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sqlcodes_sqlcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlcode',
            name='generatedby',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
