# Generated by Django 3.2 on 2021-04-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sqlcode_generatedby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SqlCode',
            new_name='Code',
        ),
    ]
