# Generated by Django 3.2 on 2021-04-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_code_generatedcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneratedCode',
            new_name='GenCode',
        ),
    ]
